### ISSUE TITLE
Always looks for new bibs created since the same date

### ISSUE THREAD

**Issue by SydneyUniLibrary-Jim** [SydneyUniLibrary/auto-holds#1]
The autoholds command always looks for bib records created since March 4, 2016. This means bib records between March 4, 2016 and when the autoholds command was last run get processed again and holds get duplicated.

The issue is caused by [line 34 of autoholds.py](https://github.com/SydneyUniLibrary/auto-holds/blob/d6973c99c0d26f9e37a8c1c8b39406ca1eb139aa/staff/management/commands/autoholds.py#L34).

Looks like we never did the code to track when the autohold was last run. 😮

**Comment by SydneyUniLibrary-Jim** [comment]
I've overhauled [autoholds.py](https://github.com/SydneyUniLibrary/auto-holds/blob/52e37249bd501a91be225896975437677cd4093d/staff/management/commands/autoholds.py). It now creates RunLog, BibLog and HoldLog objects in the database while it runs.

This is:
1. for audit and diagnostics
2. so we can track which bib records have already been processed

There is still so more to do around this:
- [ ] Store the id of the first and last bib record returned to us from the Sierra API.
- [ ] Store the created date of the first and last bib record returned to us from the SIerra API.

The Sierra API doesn't allow us to get all the bib records whose id is greater than a given bib record. So I think the approach we'll to take is to get all the bib records whose created date is greater than or equal to the latest bib record we've processed. But this might give us bib records we've already processed, so we'll need code to avoid those.

**Comment by SydneyUniLibrary-Jim** [comment]
In 383d18aeabc6a15fc984902d8ca00ec25da2b8c2 I've taught auto-holds to resume where it last left off.

When autoholds starts, it will look in the bib logs for the greatest `bib_created_at` and resume from there. When we ask the Sierra API for bibs created since then Sierra will include the last bib record we've seen, so there's code to defend against processing a bib record twice.

Before auto-holds processes its first bib record, there will not be any bib logs in the database. So instead auto-holds uses the greatest `ended_at` in the run logs.

If there aren't even any run logs because auto-holds had never actually run before, then it will resume from the current date and time. In this very first run it is unlikely to find any bib records, but it will draw a line in the sand marking from when auto-holds will start processing new bib records.

**Comment by sbennettgcpl** [comment]
Wow! you've gotten a lot done.
